Python 3.14.3 (tags/v3.14.3:323c59a, Feb  3 2026, 16:04:56) [MSC v.1944 64 bit (AMD64)] on win32
Enter "help" below or click "Help" above for more information.
>>> import socket
... 
... target = input("Enter target IP or domain: ")
... 
... print(f"\nScanning target: {target}")
... print("Scanning common ports...\n")
... 
... common_ports = [21, 22, 23, 25, 53, 80, 110, 139, 143, 443]
... 
... for port in common_ports:
...     s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
...     s.settimeout(1)
...     
...     result = s.connect_ex((target, port))
...     
...     if result == 0:
...         print(f"Port {port} is OPEN")
...     
...     s.close()
... 
